### ISSUE TITLE
Error when starting for first time, clean install

### ISSUE THREAD

**Issue by catagris** [LuisMPS/build-ui#5]
**Describe the bug**

Error when running dev command, fresh install check for checking examples.

**Error:**
```
 npm run dev                        

> demo@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /Users/wwilki/build-ui/examples/tutorial/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:358:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:668:3)
    at resolveExports (node:internal/modules/cjs/loader:529:36)
    at Module._findPath (node:internal/modules/cjs/loader:569:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:981:27)
    at mod._resolveFilename (/Users/wwilki/build-ui/examples/tutorial/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 552 (/Users/wwilki/build-ui/examples/tutorial/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
    at __nccwpck_require__ (/Users/wwilki/build-ui/examples/tutorial/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 270 (/Users/wwilki/build-ui/examples/tutorial/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
    at __nccwpck_require__ (/Users/wwilki/build-ui/examples/tutorial/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at 327 (/Users/wwilki/build-ui/examples/tutorial/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __nccwpck_require__ (/Users/wwilki/build-ui/examples/tutorial/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by LuisMPS** [comment]
Hi catagris,

Thanks for reporting.

An outdated dependency in the tutorial example was apparently causing the problem. Problem should be fixed now. 
Please let me know if it was solved for you too.
